language: ruby
script:
- jekyll build --incremental
after_success:
- git config user.email "bjacobel@gmail.com"
- git config user.name "Brian Jacobel"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git add _site
- |
  git commit -m "Jekyll build (automated commit made by Travis CI)

  ci skip"
- git push
env:
  global:
    secure: LB017WvO46i7dzVNsil80/SBs/G3G9qkkg2JTKkYRqpKx4YxXDcaAwPtPRXWmjMuggvUMeN6w0CcP5a1rr6DqJoVBbkE0wGiv3XOsid4f2cSGLEwWKEqwOlMOQIgrzohqEX1MGOJ7VEQWChHPseI3M/8OkT1UgKwz2Zi8xYevcg=
