language: ruby
sudo: false
script:
- bundle exec jekyll build --incremental
before_deploy:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- aws configure set preview.cloudfront true
deploy:
  provider: s3
  bucket: bjacobel.com
  skip_cleanup: true
  acl: public_read
  local_dir: _site
  on:
    branch: master
after_deploy:
- aws cloudfront create-invalidation --distribution-id E3927Y42SF850N --paths "/*"
