language: node_js
node_js: 6
cache: yarn
before_install:
  - npm install --global yarn
install:
  - yarn
script:
  - npm run lint
  - NODE_ENV=production npm run build
before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set preview.cloudfront true
deploy:
  provider: s3
  bucket: bjacobel.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  on:
    branch: master
after_deploy:
  - aws cloudfront create-invalidation --distribution-id E3927Y42SF850N --paths "/*"
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
