language: node_js
node_js: 10
cache: yarn
script:
  - yarn run lint
  - yarn run build
before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set preview.cloudfront true
deploy:
  provider: s3
  bucket: bjacobel.com
  skip_cleanup: true
  cache_control: "max-age=31536000"
  acl: public_read
  local_dir: dist
  on:
    branch: master
after_deploy:
  - aws cloudfront create-invalidation --distribution-id E3927Y42SF850N --paths "/index.html" "/**/index.html"
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
