name: Brian Jacobel
markdown: kramdown
timezone: America/New_York
highlighter: rouge
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      author: "Brian"

gems:
  - jekyll-sass-converter

sass:
  style: compressed

kramdown:
   input: GFM

exclude:
  - .ruby-version
  - .ruby-gemset
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - readme.md
