name: Brian Jacobel
markdown: kramdown
timezone: America/New_York
highlighter: pygments
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      author: "Brian"

gems:
  - jekyll-sass-converter

sass:
  style: compressed

kramdown:
   input: GFM
